DROP FUNCTION DOWNLOAD_EXCEL_QT_KHEN_THUONG_ALL;
/
--EndMethod--

DROP FUNCTION DT_DS_MON_MO_SEARCH_PAGE;
/
--EndMethod--

DROP FUNCTION GET_MA_DON_VI_MAX;
/
--EndMethod--

DROP FUNCTION HCTH_CONG_VAN_DEN_GET_ALL_CHI_DAO;
/
--EndMethod--

DROP FUNCTION HCTH_GIAO_NHIEM_VU_GET_ALL_PHAN_HOI;
/
--EndMethod--

DROP FUNCTION QT_CHUC_VU_GROUP_PAGE_MA;
/
--EndMethod--

DROP FUNCTION QT_NGHI_VIEC_GROUP_PAGE_MA;
/
--EndMethod--

