ALTER TABLE DM_NGANH_DAO_TAO MODIFY MA NUMBER(20,0);
/

ALTER TABLE QT_DI_NUOC_NGOAI MODIFY BAO_CAO_TEN NVARCHAR2(1000) DEFAULT 'null';
/

ALTER TABLE DT_CHUONG_TRINH_DAO_TAO ADD MA_KHOI_KIEN_THUC_CON NUMBER(22,0);
/

ALTER TABLE DT_KHUNG_DAO_TAO ADD MUC_TIEU CLOB;
/

ALTER TABLE DT_KHUNG_DAO_TAO DROP (MUC_TIEU_CHUNG,MUC_TIEU_CU_THE);
/

ALTER TABLE FW_USER_NOTIFICATION ADD GROUP NVARCHAR2(255);
/

ALTER TABLE FW_USER_NOTIFICATION DROP (READ);
/

CREATE TABLE DM_TIEP_NHAN_VE_NUOC (
    MA NVARCHAR2(2) NOT NULL,
    TEN NVARCHAR2(1000),
    CONSTRAINT PK_DM_TIEP_NHAN_VE_NUOC PRIMARY KEY (MA)
);
/

