ALTER TABLE HCTH_CONG_VAN_DEN ADD TRICH_YEU NVARCHAR2(1000);
/

ALTER TABLE HCTH_CONG_VAN_DEN MODIFY CHI_DAO NVARCHAR2(255);
/

ALTER TABLE HCTH_CONG_VAN_DEN DROP (NOI_DUNG);
/

CREATE TABLE HCTH_GIAO_NHIEM_VU (
    ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    NGUOI_TAO NUMBER(10,0) NOT NULL,
    CAN_BO_NHAN NVARCHAR2(100),
    DON_VI_NHAN NVARCHAR2(100),
    NGAY_HET_HAN NUMBER(20,0) NOT NULL,
    NOI_DUNG VARCHAR2(127.5),
    CONSTRAINT PK_HCTH_GIAO_NHIEM_VU PRIMARY KEY (ID)
);
/

ALTER TABLE QT_KY_LUAT MODIFY NOI_DUNG NVARCHAR2(1000);
/

ALTER TABLE QT_KY_LUAT DROP (CAP_QUYET_DINH);
/

ALTER TABLE QT_SANG_KIEN MODIFY TEN_SANG_KIEN NVARCHAR2(1023);
/

ALTER TABLE QT_SANG_KIEN ADD SO_QUYET_DINH NVARCHAR2(255);
/

ALTER TABLE DT_THOI_KHOA_BIEU MODIFY MA_HOC_PHAN VARCHAR2(100);
/

ALTER TABLE DT_THOI_KHOA_BIEU MODIFY MA_HOC_KY VARCHAR2(100);
/

ALTER TABLE DT_THOI_KHOA_BIEU MODIFY PHONG VARCHAR2(100);
/

ALTER TABLE DT_THOI_KHOA_BIEU MODIFY NGAY_BAT_DAU VARCHAR2(100);
/

ALTER TABLE DT_THOI_KHOA_BIEU MODIFY CBGD VARCHAR2(100);
/

CREATE TABLE DM_NGAY_LE (
    ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    NGAY NVARCHAR2(200) NOT NULL,
    MO_TA NVARCHAR2(2000) NOT NULL,
    KICH_HOAT NUMBER(1,0) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_DM_NGAY_LE PRIMARY KEY (ID)
);
/

CREATE TABLE DM_SV_KHU_VUC_TUYEN_SINH (
    MA NVARCHAR2(10) NOT NULL,
    TEN NVARCHAR2(50) NOT NULL,
    MO_TA NVARCHAR2(1024),
    KICH_HOAT NUMBER(1,0) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_DM_SV_KHU_VUC_TUYEN_SINH PRIMARY KEY (MA)
);
/

CREATE TABLE DM_HANG_THUONG_BINH (
    MA NVARCHAR2(5) NOT NULL,
    TEN NVARCHAR2(20),
    MO_TA NVARCHAR2(500),
    KICH_HOAT NUMBER(1,0) DEFAULT 1,
    CONSTRAINT PK_DM_HANG_THUONG_BINH PRIMARY KEY (MA)
);
/

CREATE TABLE TCCB_STAFF_LOG (
    EMAIL NVARCHAR2(100) NOT NULL,
    THAO_TAC NVARCHAR2(100),
    QUA_TRINH NVARCHAR2(100),
    NGAY NUMBER(20,0),
    CONSTRAINT PK_TCCB_STAFF_LOG PRIMARY KEY (EMAIL)
);
/

DROP TABLE DM_DON_VI_GUI_CV_STAGING;
/

