ALTER TABLE DM_NGANH_DAO_TAO MODIFY MA NUMBER(20,0);
/

ALTER TABLE HCTH_CONG_VAN_DI DROP (DON_VI_NHAN);
/

ALTER TABLE QT_DAO_TAO ADD MINH_CHUNG NVARCHAR2(500);
/

ALTER TABLE QT_DAO_TAO DROP (GHI_CHU_HINH_THUC,GHI_CHU_LOAI_BANG_CAP);
/

ALTER TABLE QT_SANG_KIEN ADD CAP_ANH_HUONG NUMBER(10,0);
/

CREATE TABLE HCTH_DON_VI_NHAN (
    ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    DON_VI_NHAN NUMBER(10,0) NOT NULL,
    MA NUMBER(10,0),
    LOAI NVARCHAR2(5),
    CONSTRAINT PK_HCTH_DON_VI_NHAN PRIMARY KEY (ID)
);
/

CREATE TABLE HCTH_FILE (
    ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    TEN NVARCHAR2(200) NOT NULL,
    VI_TRI NVARCHAR2(100),
    THOI_GIAN NUMBER(20,0),
    LOAI NVARCHAR2(10),
    MA NUMBER(10,0),
    CONSTRAINT PK_HCTH_FILE PRIMARY KEY (ID)
);
/

CREATE TABLE HCTH_NHIEM_VU (
    ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    NGUOI_TAO NVARCHAR2(100) NOT NULL,
    DON_VI_NHAN NVARCHAR2(100),
    NOI_DUNG NVARCHAR2(255),
    TIEU_DE NVARCHAR2(255),
    NGAY_BAT_DAU NUMBER(20,0),
    NGAY_KET_THUC NUMBER(20,0),
    DO_UU_TIEN NUMBER(5,0),
    NGAY_TAO NUMBER(20,0),
    IS_NHIEM_VU_LIEN_PHONG NUMBER(10,0) DEFAULT 0,
    CONSTRAINT PK_HCTH_NHIEM_VU PRIMARY KEY (ID)
);
/

DROP TABLE HCTH_DON_VI_NHAN_CONG_VAN;
/

DROP TABLE HCTH_FILE_CONG_VAN;
/

DROP TABLE HCTH_GIAO_NHIEM_VU;
/

